### ISSUE TITLE
[TxSubmitter] Global Singleton

### ISSUE THREAD

**Issue by dino-rodriguez** [interledgerjs/ilp-plugin-xrp-paychan-shared#22]
**Context:** I am making a plugin testing suite, which creates *n* connectors. Each automatically generates different testnet addresses.

Why does TxSubmitter have to be a singleton? Specifically, it errors if you try to make more than one instance for different addresses. In this case, each connector should have its own TxSubmitter. Two options are:

* spawn child processes for each connector when making multiple
* change TxSubmitter to not act as a singleton

**Comment by dappelt** [comment]
Hey Dino, I hope all is well. Regarding your question, XRP plugins that use the same XRP address must submit transactions in a specific order (i.e. the sequence number of consecutive transactions needs to be incremented). Otherwise, the transaction will fail. The TxSubmitter is a singleton to make sure that all XRP plugins running inside of the same process submit transactions in said order. Note that we made the assumption that different XRP plugins in the same process would always use the same XRP address.

An alternative to a singleton would be that the connector is smarter about how plugins are instantiated. The connector could make sure to pass in the same TxSubmitter object to all XRP plugins with the same address. However, we decided against that option since it would complicate the connector by introducing code specific to the type of a plugin.

For the use case that you mention, I recommend running each connector in a separate process. You can take some inspiration form [fb-service-manager](https://github.com/interledgerjs/five-bells-service-manager/blob/d0fd1664062508dffd679ecd4c15969f1553bc5a/src/service-manager.js#L62-L90) for that.

**Comment by emschwartz** [comment]
Thanks @dappelt for weighing in!

Given that reasoning, what if we allow an XRP address to be passed into the `createSubmitter` function so it can ensure that every address only gets one, but that would also support having multiple addresses managed by the same process?

**Comment by dino-rodriguez** [comment]
Thank you @dappelt! That makes sense. I opted to edit TxSubmitter, but the forking is still useful because there are other singletons in the connector (like Prometheus client)

@emschwartz did this a while back, will PR now
